apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: myapp-deploymentconfig
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
